stellar/actions

.github/workflows/rust-bump-version.yml
Require type of version provided to bump version to be a string.
The type is required.
=> Require type of version provided to bump version to be a string

.github/workflows/rust-bump-version.yml, .github/workflows/rust-set-rust-version.yml
Set target-dir for cargo bin installs in workflows.
So that the cargo bin installs are cached.
=> Set target-dir for cargo bin installs in workflows

README.md, rust-workspace-publish-dry-run/action.yml
Add action that runs package verification on a workspace
So that on release branches of our crates we can have confidence that they will compile before starting the publish process.
Unfortunately there is no officially supported or even community specified way to do this, so the process is somewhat of a hack. The process relies entirely on the vendor directory feature of cargo however, which is an official component of cargo and so this hack should be relatively stable.
=> Add action that runs package verification on a workspace

rust-workspace-publish-dry-run/action.yml
Add cargo package options as an input to the workspace publish dry run
So that workflows can specify a target.
=> Add cargo package options as an input to the workspace publish dry run

rust-workspace-publish-dry-run/action.yml
Remove the .bak file created as a temporary file.
So that it doesn't make the git repo dirty.
=> Remove the .bak file so it does not make the git repo dirty

rust-workspace-publish-dry-run/action.yml
Change name of `options` input to `cargo-package-options`.
That's the name of the input used inside the composite action, and the meta details describing the input is wrong.
=> Fix cargo-package-options input to workspace publish dry run action

.github/workflows/rust-bump-version.yml
Add @ symbol to username in bump version workflow.
So that the triggering user is mentioned on the opened PR and notified of it being opened.
=> Add @ symbol to username in bump version workflow

.github/workflows/rust-bump-version.yml
Add release instructions to the PR that the bump version workflow opens.
To help people get to the next step.
=> Add release instructions to the bump version PR

.github/workflows/rust-publish-dry-run.yml
Make runs-on input not required for publish dry run.
So that repos do not have to specify the value. Even if there is a default value, the required flag forces it to be provided.
=> Make runs-on input not required for publish dry run

.github/workflows/rust-publish-dry-run.yml
Rename publish job to publish-dry-run in dry run workflow.
To make the job name less confusing.
=> Rename publish job to publish-dry-run in dry run workflow

.github/workflows/rust-publish-dry-run.yml
Add options to configure cargo hack features to dry run publish workflow.
Some workflows need to be able to configure the cargo hack feature selection.
=> Add options to configure cargo hack features to dry run publish workflow

.github/workflows/rust-publish-dry-run.yml
Give repos more control over feature sets run during dry run.
Some repos need to turn off feature powerset for some builds.
=> Give repos more control over feature sets run during dry run

.github/workflows/rust-publish-dry-run.yml
Add complete job to rust-publish-dry-run workflow.
Our repos wait on all complete jobs being finished before a pull request can merge. This requires that the publish-dry-run job finishes before allowing a bump verison pull request to merge.
=> Require publish-dry-run to complete on repos that wait on complete

README.md
Change the link in the readme for the rust-cache action so that it links to a page that shows the rust-cache readme.
The rust-cache readme has usage instructions. It is better to link a user to the usage instructions than it is to link them to the code.
=> Change link for rust-cache to its readme

.github/workflows/rust-bump-version.yml
Make the base branch of bump version configurable.
So that repos like stellar/wasmi can set the base branch.
=> Make the base branch of bump version configurable

.github/workflows/rust-bump-version.yml
Still open a PR if bump version has errors.
Sometimes bumping versions can encounter problems. We should open a PR with what it could achieve and let a human progress things.
=> Still open a PR if bump version has errors

.github/workflows/rust-publish-dry-run.yml
Remove unnecessary complete job.
It makes builds noisy in workflows that call it.
=> Remove unnecessary complete job

README-rust-release.md
Remove comment from release notes that says the process doesn't support patching past releases.
That process is now supported.
=> Remove out-dated comment from release notes

rust-cache/action.yml
Use shasum on macOS to verify the sha256 of sccache, and install the appropriate versions of sccache for the different runners OSes.
macOS has shasum, not sha256sum. We install a binary sccache and so need to install the appropriate versions for the different operating systems.
=> Add support for macOS, Windows to rust-cache

.github/workflows/rust-bump-version.yml, .github/workflows/rust-publish-dry-run.yml, .github/workflows/rust-publish.yml, .github/workflows/rust-set-rust-version.yml
Use stellar/binaries for binary installs.
Avoiding long (5m+) compile times in release processes.
=> Use stellar/binaries for binary installs

.github/workflows/rust-publish-dry-run.yml
Make publish dry run work with all platforms.
So that we verify a release is ready and safe for all platforms before release.
=> Make publish dry run work with all platforms

.github/workflows/rust-publish-dry-run.yml
Fixes the error seen here where the git repo is removed, but not the git revision - https://github.com/stellar/rs-soroban-env/actions/runs/3517668668/jobs/5895702845.
=> Remove rev when we remove git repo

.github/workflows/rust-bump-version.yml
Use cargo-edit instead of cargo-workspaces for bump version.
Cargo workspaces does not support workspaces that use workspace inheritance, while cargo edit's `cargo set-version` command does.
=> Use cargo-edit instead of cargo-workspaces for bump version

.github/workflows/rust-publish-dry-run.yml
Run apt-get update before apt-get install.
We're seeing failures which are likely to do with the apt-get repositories that are cached being out of date. It's common practice to run update before install.
=> Make apt-get installs more resilient

.github/workflows/rust-publish-dry-run-v2.yml, .github/workflows/rust-publish-dry-run.yml, README-rust-release.md, README.md, rust-publish-dry-run-v2/workflow.yml
Add Publish Dry Run v2 that publishes an explicit list of crates in an explicit order provided by inputs, rather than calculated using tooling.
The existing dry run script is dependent on cargo being able to package crates without talking to crates.io. However, cargo does talk to crates.io to verify crates when building a lock file for a package, which is something it does when packaging binaries. Because of this the existing dry run script only works for libraries and not binaries.
The existing dry run script doesn't need to be told what crates to publish or what order to publish them in. It relies on cargo figuring that out, and because cargo doesn't talk to crates.io, it doesn't matter that none of the crates are published yet.
For binary crates we can't rely on cargo to package a …
=> Add Publish Dry Run v2

README.md, rust-check-git-rev-deps/README.md, rust-check-git-rev-deps/action.yml, rust-check-git-rev-deps/check.sh
Add action that checks git rev deps for whether they are likely to be orphaned.
On a number of occassions we've accidentally committed a reference to a dependency that belongs to a commit on a pull request. The pull request was then closed, and while the commit lives forever in the Git repository, it is not seen by tools that do not fetch orphaned commits.
Close #55
=> Add action that checks git rev deps for orphan likeliness

rust-check-git-rev-deps/check.sh
Remove verbose git output and don't checkout each ref being checked.
```diff
@@ -1,137 +1,32 @@
Checking https://github.com/stellar/rs-stellar-strkey @ e6ba45c60c16de28c7522586b80ed0150157df73
-Cloning into '/var/folders/75/wqcxsy716bq0qht_8jtvw85h0000gn/T/tmp.ZjHN6hJp'...
-remote: Enumerating objects: 204, done.
-remote: Counting objects: 100% (140/140), done.
-remote: Compressing objects: 100% (91/91), done.
-remote: Total 204 (delta 90), reused 72 (delta 44), pack-reused 64
-Receiving objects: 100% (204/204), 52.70 KiB | 2.03 MiB/s, done.
-Resolving deltas: 100% (102/102), done.
-/var/folders/75/wqcxsy716bq0qht_8jtvw85h0000gn/T/tmp.ZjHN6hJp ~/Code/rs-soroban-env
-Updated 0 paths from the index
-Checking is in heads/main
Commit is in the history of heads/main.
-HEAD is now at 317f768 …
```
=> Simplify output of rust-check-git-rev-deps action

rust-check-git-rev-deps/check.sh
Don't output a warning when a branch/tag doesn't contain the commit. Only output the message if no branches/tags are found that contain the commit.
And fetch the commit before testing it.
The message reads like a warning, and so it sounds like something is wrong when it is really informational.
If we fetch the commit first we can signal when a commit is entirely missing and that makes following error messages less confusing when it happens.
cc @graydon
=> Reduce noisy warning-like messages in rust git rev action

.github/workflows/rust-publish-dry-run.yml
Create vendor directory manually.
It'll only be created in the existing flow if a crate has dependencies, but it is needed in later steps of the flow in all cases. This is causing publish dry run to fail for crates with no deps because the vendor directory doesn't exist.
=> Fix publish dry run for crates with no deps

.github/workflows/rust-publish-dry-run-v2.yml
Change version lookup in publish dry run v2 workflow to ignore deps when looking up versions of crates that are local to the repo.
Without constraining the version lookup to the crates in the current repo the lookup may return multiple versions if a crate has previously lived in another repo or if a crate in this repo is dependent on a previous version of a crate that is published to crates.io.
=> Fix version look up in publish dry run to ignore deps

.github/workflows/rust-bump-version.yml, .github/workflows/rust-publish-dry-run-v2.yml, .github/workflows/rust-publish-dry-run.yml, .github/workflows/rust-publish.yml, .github/workflows/rust-set-rust-version.yml
Update binaries across all workflows.
The latest version of the binaries has binaries for ARM64 runners, and macos runners are primarily ARM64 on GitHub now.
=> Update binaries across all workflows

.github/workflows/rust-publish-dry-run-v2.yml
Outdated versions of `make` cause problems when building certain binaries ([like soroban-cli](https://github.com/stellar/soroban-cli/actions/runs/7994869579/job/21833922140)).
This also enables debugging on failures via `RUST_BACKTRACE`.
=> Update make prior to dry-runs on macOS.

.github/workflows/rust-publish-dry-run-v2.yml
We need this because the cli requires `libudev-dev`, a ledger dependency.
=> Add option to install additional .deb packages.

.github/workflows/rust-publish-dry-run-v2.yml, .github/workflows/rust-publish-dry-run.yml
Make publish-dry-run-v2 work without a list of crates and deprecate v1.
v1 was able to work out what crates to publish, but it had an issue that showed up only on some repos where it would trigger cargo looking up crates on crates.io before they had been published which would fail because the process of packaging the crates for a dry run wasn't preserving the order or using the local registry.
v2 was written to replace v1 but v2 was written requiring an explicit list of crates in the order to publish to avoid the lookups on crates.io.
This change makes v2 no longer require the explicit list by using cargo-workspaces (the tool we use to do actual publishes) to produce a list of crates that need publishing in the order they need publishing.
With this change v2 now works with the same inputs …
=> Make publish-dry-run-v2 work without a list of crates and deprecate v1

.github/workflows/rust-publish-dry-run-v2.yml
Update cargo-workspaces to 0.3.4 and rely on the list command getting the crates in publish order.
(And fix the cargo workspaces call for windows that needs to call the binary directory rather via the cargo plugin system.)
https://github.com/pksunkara/cargo-workspaces/issues/155 was implemented in cargo-workspaces 0.3.4 providing the crate list returned from the list command in publish order, so there is no longer the need to use the exec command to order the crates.
Dependent on:
- https://github.com/pksunkara/cargo-workspaces/issues/155
- https://github.com/stellar/binaries/pull/25
=> Simplify publish-dry-run-v2 crate selection using cargo-workspaces 0.3.4

.github/workflows/rust-bump-version.yml
Set the userid on the GH bot for pushes in the bump-version action and remove modifications to global git config.
The userid is the recommended way to reference the GH bot now:
- https://github.com/actions/checkout/pull/1707
The accompanying changes to remove the `--global` makes our use consistent with the PR above's recommendations.
We started to see failing builds that do a git push as the GH bot, e.g.:
- https://github.com/stellar/rs-soroban-env/actions/runs/10446231617/job/28923346397
Nothing changes on our side that I'm aware of, although I have an ask out to ops at the thread below to confirm:
- https://stellarfoundation.slack.com/archives/C02U19A2A/p1723857725537729
Folks in this community forum got it working again by removing modifications to the global git config:
- …
=> Set the userid on the GH bot for pushes in bump-version

.github/workflows/rust-bump-version.yml
Update rust-bump-version.yml to use actions/checkout@v4.
GitHub Support suggested it could fix the permissions issues we started encountering a few days ago.
=> Update rust-bump-version.yml to use actions/checkout@v4

rust-cache/action.yml
Sccache is now compatible with ARM runners.
I restructured the way env vars are defined because we need to run uname to check for machine hardware
=> Update rust cache action for Linux ARM

.github/workflows/rust-publish-dry-run-v2.yml
I was seeing the following failure in the stellar-cli CI. Other occurances of this seemed to be fix by first updating apt-get before installing the packages.
```
Run sudo apt-get -y install libudev-dev libdbus-1-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
libdbus-1-dev libudev-dev
0 upgraded, 2 newly installed, 0 to remove and 29 not upgraded.
Need to get 212 kB of archives.
After this operation, 1203 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 libdbus-1-dev amd64 1.14.[10](https://github.com/stellar/stellar-cli/actions/runs/13182781772/job/36800135945#step:8:11)-4ubuntu4.1 [190 …
```
=> Update apt-get before installing additional deb packages

rust-cache/action.yml
Github deprecated actions/cache@v3, so this bumps us to v4.
=> Use github actions/cache@v4 as required by github deprecation

.github/workflows/rust-bump-version.yml
Add permissions for actions, contents, and pull-requests to the rust-bump-version workflow.
Something has changed with GitHub, and explicit permissions are required for the workflow to create commits and pull requests when bumping versions when being created from previous tags.
=> Add permissions to rust-bump-version workflow
